import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
import main


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 1012)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.shuchu = QtWidgets.QTableWidget(self.centralwidget)
        self.shuchu.setGeometry(QtCore.QRect(1, 1, 511, 991))
        self.shuchu.setStyleSheet("QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
                                  "    \n"
                                  "              font-size: 19px;                /*11榜*/\n"
                                  "          border: 1px solid rgb(255, 255, 255);\n"
                                  "       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
                                  "        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
                                  "          min-height:40px;\n"
                                  "           \n"
                                  "} \n"
                                  " \n"
                                  " \n"
                                  "QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
                                  "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                  "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                  "        color: rgb(2, 65, 132);\n"
                                  "        background: transparent;\n"
                                  "        padding-left: 2px;\n"
                                  "        min-width:60px;\n"
                                  "}\n"
                                  "QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
                                  "        color: white;                            /*字体白色*/\n"
                                  "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                  "}\n"
                                  "QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
                                  "        color: white;\n"
                                  "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                  "}\n"
                                  "QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
                                  "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                  "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                  "        color: rgb(2, 65, 132);\n"
                                  "        background: rgb(255, 255, 255,180);\n"
                                  "        padding-top: 3px;\n"
                                  "        min-width:60px;\n"
                                  "        \n"
                                  "}\n"
                                  "QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
                                  "        color: white;                            /*字体白色*/\n"
                                  "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                  "}\n"
                                  "QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
                                  "        color: white;\n"
                                  "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                  "}\n"
                                  " \n"
                                  " \n"
                                  "QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
                                  "        width: 13px;\n"
                                  "        height: 11px;\n"
                                  "        padding-right: 0px;                         /*设置右内边距*/\n"
                                  "        image: url(:/arrow_up.png);\n"
                                  "        subcontrol-position: center right;\n"
                                  "}\n"
                                  "QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
                                  "     \n"
                                  "}\n"
                                  "QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
                                  "        width: 13px;\n"
                                  "        height: 11px;\n"
                                  "        padding-right: 10px;\n"
                                  "        image: url(:/arrow_down.png);\n"
                                  "        subcontrol-position: center right;\n"
                                  "}\n"
                                  "QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
                                  "     \n"
                                  "}\n"
                                  "QTableWidget,QTableView {\n"
                                  "                font-size: 17px;                /*10榜*/                \n"
                                  "                color : rgb(1,37,116);                \n"
                                  "        border: 2px solid rgb(100, 188, 238);        \n"
                                  "        background: rgb(248,248,248);\n"
                                  "        gridline-color: rgb(196,226,255);    \n"
                                  "        text-align: center;    \n"
                                  "        outline:0px;            /*禁止焦点*/\n"
                                  "        \n"
                                  "}\n"
                                  "QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
                                  "        padding-left: 5px;\n"
                                  "        padding-right: 5px;\n"
                                  "        border: none; \n"
                                  "        background: rgba(251,251,253,200);\n"
                                  "       \n"
                                  "       /* border-right: 1px solid rgb(100, 188, 238); */\n"
                                  "        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
                                  "}\n"
                                  "QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
                                  "        background: rgba(207,230,253,200);\n"
                                  "        color : rgb(1,37,116);                \n"
                                  "}\n"
                                  " \n"
                                  " \n"
                                  "QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
                                  "{ \n"
                                  "    background: rgb(250,250,250); \n"
                                  "}\n"
                                  " \n"
                                  "QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
                                  "{ \n"
                                  "    background: rgb(240,247,254); \n"
                                  "}\n"
                                  "QScrollBar:vertical\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,0%);\n"
                                  "    margin:0px,0px,0px,0px;\n"
                                  "    padding-top:9px; \n"
                                  "    padding-bottom:9px;\n"
                                  "}\n"
                                  "QScrollBar::handle:vertical\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,25%);\n"
                                  "    border-radius:4px; \n"
                                  "    min-height:20;\n"
                                  "}\n"
                                  "QScrollBar::handle:vertical:hover\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,50%);  \n"
                                  "    border-radius:4px;\n"
                                  "    min-height:20;\n"
                                  "}\n"
                                  "QScrollBar::add-line:vertical\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/3.png);\n"
                                  "    subcontrol-position:bottom;\n"
                                  "}\n"
                                  "QScrollBar::sub-line:vertical\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/1.png);\n"
                                  "    subcontrol-position:top;\n"
                                  "}\n"
                                  "QScrollBar::add-line:vertical:hover \n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/4.png);\n"
                                  "    subcontrol-position:bottom;\n"
                                  "}\n"
                                  "QScrollBar::sub-line:vertical:hover\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/2.png);\n"
                                  "    subcontrol-position:top;\n"
                                  "}\n"
                                  "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
                                  "{\n"
                                  "    background:rgba(0,0,0,10%);\n"
                                  "    border-radius:4px;\n"
                                  "}")
        self.shuchu.setObjectName("shuchu")
        self.shuchu.setColumnCount(4)
        self.shuchu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.shuchu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.shuchu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.shuchu.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.shuchu.setHorizontalHeaderItem(3, item)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(520, 0, 278, 831))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_6.setStyleSheet("QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
                                         "    \n"
                                         "              font-size: 19px;                /*11榜*/\n"
                                         "          border: 1px solid rgb(255, 255, 255);\n"
                                         "       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
                                         "        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
                                         "          min-height:40px;\n"
                                         "           \n"
                                         "} \n"
                                         " \n"
                                         " \n"
                                         "QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
                                         "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                         "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                         "        color: rgb(2, 65, 132);\n"
                                         "        background: transparent;\n"
                                         "        padding-left: 2px;\n"
                                         "        min-width:60px;\n"
                                         "}\n"
                                         "QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
                                         "        color: white;                            /*字体白色*/\n"
                                         "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                         "}\n"
                                         "QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
                                         "        color: white;\n"
                                         "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                         "}\n"
                                         "QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
                                         "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                         "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                         "        color: rgb(2, 65, 132);\n"
                                         "        background: rgb(255, 255, 255,180);\n"
                                         "        padding-top: 3px;\n"
                                         "        min-width:60px;\n"
                                         "        \n"
                                         "}\n"
                                         "QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
                                         "        color: white;                            /*字体白色*/\n"
                                         "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                         "}\n"
                                         "QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
                                         "        color: white;\n"
                                         "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                         "}\n"
                                         " \n"
                                         " \n"
                                         "QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
                                         "        width: 13px;\n"
                                         "        height: 11px;\n"
                                         "        padding-right: 0px;                         /*设置右内边距*/\n"
                                         "        image: url(:/arrow_up.png);\n"
                                         "        subcontrol-position: center right;\n"
                                         "}\n"
                                         "QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
                                         "     \n"
                                         "}\n"
                                         "QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
                                         "        width: 13px;\n"
                                         "        height: 11px;\n"
                                         "        padding-right: 10px;\n"
                                         "        image: url(:/arrow_down.png);\n"
                                         "        subcontrol-position: center right;\n"
                                         "}\n"
                                         "QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
                                         "     \n"
                                         "}\n"
                                         "QTableWidget,QTableView {\n"
                                         "                font-size: 17px;                /*10榜*/                \n"
                                         "                color : rgb(1,37,116);                \n"
                                         "        border: 2px solid rgb(100, 188, 238);        \n"
                                         "        background: rgb(248,248,248);\n"
                                         "        gridline-color: rgb(196,226,255);    \n"
                                         "        text-align: center;    \n"
                                         "        outline:0px;            /*禁止焦点*/\n"
                                         "        \n"
                                         "}\n"
                                         "QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
                                         "        padding-left: 5px;\n"
                                         "        padding-right: 5px;\n"
                                         "        border: none; \n"
                                         "        background: rgba(251,251,253,200);\n"
                                         "       \n"
                                         "       /* border-right: 1px solid rgb(100, 188, 238); */\n"
                                         "        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
                                         "}\n"
                                         "QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
                                         "        background: rgba(207,230,253,200);\n"
                                         "        color : rgb(1,37,116);                \n"
                                         "}\n"
                                         " \n"
                                         " \n"
                                         "QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
                                         "{ \n"
                                         "    background: rgb(250,250,250); \n"
                                         "}\n"
                                         " \n"
                                         "QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
                                         "{ \n"
                                         "    background: rgb(240,247,254); \n"
                                         "}\n"
                                         "QScrollBar:vertical\n"
                                         "{\n"
                                         "    width:8px;\n"
                                         "    background:rgba(0,0,0,0%);\n"
                                         "    margin:0px,0px,0px,0px;\n"
                                         "    padding-top:9px; \n"
                                         "    padding-bottom:9px;\n"
                                         "}\n"
                                         "QScrollBar::handle:vertical\n"
                                         "{\n"
                                         "    width:8px;\n"
                                         "    background:rgba(0,0,0,25%);\n"
                                         "    border-radius:4px; \n"
                                         "    min-height:20;\n"
                                         "}\n"
                                         "QScrollBar::handle:vertical:hover\n"
                                         "{\n"
                                         "    width:8px;\n"
                                         "    background:rgba(0,0,0,50%);  \n"
                                         "    border-radius:4px;\n"
                                         "    min-height:20;\n"
                                         "}\n"
                                         "QScrollBar::add-line:vertical\n"
                                         "{\n"
                                         "    height:9px;width:8px;\n"
                                         "    border-image:url(:/images/a/3.png);\n"
                                         "    subcontrol-position:bottom;\n"
                                         "}\n"
                                         "QScrollBar::sub-line:vertical\n"
                                         "{\n"
                                         "    height:9px;width:8px;\n"
                                         "    border-image:url(:/images/a/1.png);\n"
                                         "    subcontrol-position:top;\n"
                                         "}\n"
                                         "QScrollBar::add-line:vertical:hover \n"
                                         "{\n"
                                         "    height:9px;width:8px;\n"
                                         "    border-image:url(:/images/a/4.png);\n"
                                         "    subcontrol-position:bottom;\n"
                                         "}\n"
                                         "QScrollBar::sub-line:vertical:hover\n"
                                         "{\n"
                                         "    height:9px;width:8px;\n"
                                         "    border-image:url(:/images/a/2.png);\n"
                                         "    subcontrol-position:top;\n"
                                         "}\n"
                                         "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
                                         "{\n"
                                         "    background:rgba(0,0,0,10%);\n"
                                         "    border-radius:4px;\n"
                                         "}")
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.tableWidget_6)
        self.guanjianzi = QtWidgets.QTableWidget(self.widget)
        self.guanjianzi.setStyleSheet("QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
                                      "    \n"
                                      "              font-size: 19px;                /*11榜*/\n"
                                      "          border: 1px solid rgb(255, 255, 255);\n"
                                      "       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
                                      "        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
                                      "          min-height:40px;\n"
                                      "           \n"
                                      "} \n"
                                      " \n"
                                      " \n"
                                      "QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
                                      "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                      "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                      "        color: rgb(2, 65, 132);\n"
                                      "        background: transparent;\n"
                                      "        padding-left: 2px;\n"
                                      "        min-width:60px;\n"
                                      "}\n"
                                      "QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
                                      "        color: white;                            /*字体白色*/\n"
                                      "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                      "}\n"
                                      "QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
                                      "        color: white;\n"
                                      "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                      "}\n"
                                      "QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
                                      "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                      "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                      "        color: rgb(2, 65, 132);\n"
                                      "        background: rgb(255, 255, 255,180);\n"
                                      "        padding-top: 3px;\n"
                                      "        min-width:60px;\n"
                                      "        \n"
                                      "}\n"
                                      "QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
                                      "        color: white;                            /*字体白色*/\n"
                                      "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                      "}\n"
                                      "QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
                                      "        color: white;\n"
                                      "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                      "}\n"
                                      " \n"
                                      " \n"
                                      "QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
                                      "        width: 13px;\n"
                                      "        height: 11px;\n"
                                      "        padding-right: 0px;                         /*设置右内边距*/\n"
                                      "        image: url(:/arrow_up.png);\n"
                                      "        subcontrol-position: center right;\n"
                                      "}\n"
                                      "QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
                                      "     \n"
                                      "}\n"
                                      "QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
                                      "        width: 13px;\n"
                                      "        height: 11px;\n"
                                      "        padding-right: 10px;\n"
                                      "        image: url(:/arrow_down.png);\n"
                                      "        subcontrol-position: center right;\n"
                                      "}\n"
                                      "QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
                                      "     \n"
                                      "}\n"
                                      "QTableWidget,QTableView {\n"
                                      "                font-size: 17px;                /*10榜*/                \n"
                                      "                color : rgb(1,37,116);                \n"
                                      "        border: 2px solid rgb(100, 188, 238);        \n"
                                      "        background: rgb(248,248,248);\n"
                                      "        gridline-color: rgb(196,226,255);    \n"
                                      "        text-align: center;    \n"
                                      "        outline:0px;            /*禁止焦点*/\n"
                                      "        \n"
                                      "}\n"
                                      "QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
                                      "        padding-left: 5px;\n"
                                      "        padding-right: 5px;\n"
                                      "        border: none; \n"
                                      "        background: rgba(251,251,253,200);\n"
                                      "       \n"
                                      "       /* border-right: 1px solid rgb(100, 188, 238); */\n"
                                      "        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
                                      "}\n"
                                      "QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
                                      "        background: rgba(207,230,253,200);\n"
                                      "        color : rgb(1,37,116);                \n"
                                      "}\n"
                                      " \n"
                                      " \n"
                                      "QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
                                      "{ \n"
                                      "    background: rgb(250,250,250); \n"
                                      "}\n"
                                      " \n"
                                      "QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
                                      "{ \n"
                                      "    background: rgb(240,247,254); \n"
                                      "}\n"
                                      "QScrollBar:vertical\n"
                                      "{\n"
                                      "    width:8px;\n"
                                      "    background:rgba(0,0,0,0%);\n"
                                      "    margin:0px,0px,0px,0px;\n"
                                      "    padding-top:9px; \n"
                                      "    padding-bottom:9px;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical\n"
                                      "{\n"
                                      "    width:8px;\n"
                                      "    background:rgba(0,0,0,25%);\n"
                                      "    border-radius:4px; \n"
                                      "    min-height:20;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical:hover\n"
                                      "{\n"
                                      "    width:8px;\n"
                                      "    background:rgba(0,0,0,50%);  \n"
                                      "    border-radius:4px;\n"
                                      "    min-height:20;\n"
                                      "}\n"
                                      "QScrollBar::add-line:vertical\n"
                                      "{\n"
                                      "    height:9px;width:8px;\n"
                                      "    border-image:url(:/images/a/3.png);\n"
                                      "    subcontrol-position:bottom;\n"
                                      "}\n"
                                      "QScrollBar::sub-line:vertical\n"
                                      "{\n"
                                      "    height:9px;width:8px;\n"
                                      "    border-image:url(:/images/a/1.png);\n"
                                      "    subcontrol-position:top;\n"
                                      "}\n"
                                      "QScrollBar::add-line:vertical:hover \n"
                                      "{\n"
                                      "    height:9px;width:8px;\n"
                                      "    border-image:url(:/images/a/4.png);\n"
                                      "    subcontrol-position:bottom;\n"
                                      "}\n"
                                      "QScrollBar::sub-line:vertical:hover\n"
                                      "{\n"
                                      "    height:9px;width:8px;\n"
                                      "    border-image:url(:/images/a/2.png);\n"
                                      "    subcontrol-position:top;\n"
                                      "}\n"
                                      "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
                                      "{\n"
                                      "    background:rgba(0,0,0,10%);\n"
                                      "    border-radius:4px;\n"
                                      "}")
        self.guanjianzi.setObjectName("guanjianzi")
        self.guanjianzi.setColumnCount(2)
        self.guanjianzi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.guanjianzi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.guanjianzi.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.guanjianzi)
        self.fenjiefu = QtWidgets.QTableWidget(self.widget)
        self.fenjiefu.setStyleSheet("QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
                                    "    \n"
                                    "              font-size: 19px;                /*11榜*/\n"
                                    "          border: 1px solid rgb(255, 255, 255);\n"
                                    "       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
                                    "        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
                                    "          min-height:40px;\n"
                                    "           \n"
                                    "} \n"
                                    " \n"
                                    " \n"
                                    "QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
                                    "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                    "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                    "        color: rgb(2, 65, 132);\n"
                                    "        background: transparent;\n"
                                    "        padding-left: 2px;\n"
                                    "        min-width:60px;\n"
                                    "}\n"
                                    "QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
                                    "        color: white;                            /*字体白色*/\n"
                                    "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                    "}\n"
                                    "QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
                                    "        color: white;\n"
                                    "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                    "}\n"
                                    "QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
                                    "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                    "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                    "        color: rgb(2, 65, 132);\n"
                                    "        background: rgb(255, 255, 255,180);\n"
                                    "        padding-top: 3px;\n"
                                    "        min-width:60px;\n"
                                    "        \n"
                                    "}\n"
                                    "QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
                                    "        color: white;                            /*字体白色*/\n"
                                    "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                    "}\n"
                                    "QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
                                    "        color: white;\n"
                                    "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                    "}\n"
                                    " \n"
                                    " \n"
                                    "QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
                                    "        width: 13px;\n"
                                    "        height: 11px;\n"
                                    "        padding-right: 0px;                         /*设置右内边距*/\n"
                                    "        image: url(:/arrow_up.png);\n"
                                    "        subcontrol-position: center right;\n"
                                    "}\n"
                                    "QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
                                    "     \n"
                                    "}\n"
                                    "QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
                                    "        width: 13px;\n"
                                    "        height: 11px;\n"
                                    "        padding-right: 10px;\n"
                                    "        image: url(:/arrow_down.png);\n"
                                    "        subcontrol-position: center right;\n"
                                    "}\n"
                                    "QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
                                    "     \n"
                                    "}\n"
                                    "QTableWidget,QTableView {\n"
                                    "                font-size: 17px;                /*10榜*/                \n"
                                    "                color : rgb(1,37,116);                \n"
                                    "        border: 2px solid rgb(100, 188, 238);        \n"
                                    "        background: rgb(248,248,248);\n"
                                    "        gridline-color: rgb(196,226,255);    \n"
                                    "        text-align: center;    \n"
                                    "        outline:0px;            /*禁止焦点*/\n"
                                    "        \n"
                                    "}\n"
                                    "QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
                                    "        padding-left: 5px;\n"
                                    "        padding-right: 5px;\n"
                                    "        border: none; \n"
                                    "        background: rgba(251,251,253,200);\n"
                                    "       \n"
                                    "       /* border-right: 1px solid rgb(100, 188, 238); */\n"
                                    "        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
                                    "}\n"
                                    "QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
                                    "        background: rgba(207,230,253,200);\n"
                                    "        color : rgb(1,37,116);                \n"
                                    "}\n"
                                    " \n"
                                    " \n"
                                    "QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
                                    "{ \n"
                                    "    background: rgb(250,250,250); \n"
                                    "}\n"
                                    " \n"
                                    "QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
                                    "{ \n"
                                    "    background: rgb(240,247,254); \n"
                                    "}\n"
                                    "QScrollBar:vertical\n"
                                    "{\n"
                                    "    width:8px;\n"
                                    "    background:rgba(0,0,0,0%);\n"
                                    "    margin:0px,0px,0px,0px;\n"
                                    "    padding-top:9px; \n"
                                    "    padding-bottom:9px;\n"
                                    "}\n"
                                    "QScrollBar::handle:vertical\n"
                                    "{\n"
                                    "    width:8px;\n"
                                    "    background:rgba(0,0,0,25%);\n"
                                    "    border-radius:4px; \n"
                                    "    min-height:20;\n"
                                    "}\n"
                                    "QScrollBar::handle:vertical:hover\n"
                                    "{\n"
                                    "    width:8px;\n"
                                    "    background:rgba(0,0,0,50%);  \n"
                                    "    border-radius:4px;\n"
                                    "    min-height:20;\n"
                                    "}\n"
                                    "QScrollBar::add-line:vertical\n"
                                    "{\n"
                                    "    height:9px;width:8px;\n"
                                    "    border-image:url(:/images/a/3.png);\n"
                                    "    subcontrol-position:bottom;\n"
                                    "}\n"
                                    "QScrollBar::sub-line:vertical\n"
                                    "{\n"
                                    "    height:9px;width:8px;\n"
                                    "    border-image:url(:/images/a/1.png);\n"
                                    "    subcontrol-position:top;\n"
                                    "}\n"
                                    "QScrollBar::add-line:vertical:hover \n"
                                    "{\n"
                                    "    height:9px;width:8px;\n"
                                    "    border-image:url(:/images/a/4.png);\n"
                                    "    subcontrol-position:bottom;\n"
                                    "}\n"
                                    "QScrollBar::sub-line:vertical:hover\n"
                                    "{\n"
                                    "    height:9px;width:8px;\n"
                                    "    border-image:url(:/images/a/2.png);\n"
                                    "    subcontrol-position:top;\n"
                                    "}\n"
                                    "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
                                    "{\n"
                                    "    background:rgba(0,0,0,10%);\n"
                                    "    border-radius:4px;\n"
                                    "}")
        self.fenjiefu.setObjectName("fenjiefu")
        self.fenjiefu.setColumnCount(2)
        self.fenjiefu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.fenjiefu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fenjiefu.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.fenjiefu)
        self.guanxi = QtWidgets.QTableWidget(self.widget)
        self.guanxi.setStyleSheet("QHeaderView{                            /*设置标题(包括垂直+水平的)*/\n"
                                  "    \n"
                                  "              font-size: 19px;                /*11榜*/\n"
                                  "          border: 1px solid rgb(255, 255, 255);\n"
                                  "       /* border-bottom: 2px solid rgb(35, 100, 224);         下边框深蓝色*/\n"
                                  "        background: rgb(100, 188, 238);                /*背景浅蓝色*/ \n"
                                  "          min-height:40px;\n"
                                  "           \n"
                                  "} \n"
                                  " \n"
                                  " \n"
                                  "QHeaderView::section:horizontal {                     /*设置标题(水平的)*/\n"
                                  "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                  "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                  "        color: rgb(2, 65, 132);\n"
                                  "        background: transparent;\n"
                                  "        padding-left: 2px;\n"
                                  "        min-width:60px;\n"
                                  "}\n"
                                  "QHeaderView::section:horizontal:hover {            /*设置鼠标停留状态*/\n"
                                  "        color: white;                            /*字体白色*/\n"
                                  "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                  "}\n"
                                  "QHeaderView::section:horizontal:pressed {            /*设置鼠标按下状态*/\n"
                                  "        color: white;\n"
                                  "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                  "}\n"
                                  "QHeaderView::section:vertical {                     /*设置标题(垂直的)*/\n"
                                  "        border: 1px solid rgb(255, 255, 255);             /*白色间隔*/\n"
                                  "          border-bottom: 0px;                            /*下边框不需要颜色*/\n"
                                  "        color: rgb(2, 65, 132);\n"
                                  "        background: rgb(255, 255, 255,180);\n"
                                  "        padding-top: 3px;\n"
                                  "        min-width:60px;\n"
                                  "        \n"
                                  "}\n"
                                  "QHeaderView::section:vertical:hover {            /*设置鼠标停留状态*/\n"
                                  "        color: white;                            /*字体白色*/\n"
                                  "        background: rgb(11,82,202);                /*背景深蓝色*/\n"
                                  "}\n"
                                  "QHeaderView::section:vertical:pressed {            /*设置鼠标按下状态*/\n"
                                  "        color: white;\n"
                                  "        background: rgb(39,106,220);                /*背景深蓝色减一点*/\n"
                                  "}\n"
                                  " \n"
                                  " \n"
                                  "QHeaderView::up-arrow {                        /*设置向上排序指针*/\n"
                                  "        width: 13px;\n"
                                  "        height: 11px;\n"
                                  "        padding-right: 0px;                         /*设置右内边距*/\n"
                                  "        image: url(:/arrow_up.png);\n"
                                  "        subcontrol-position: center right;\n"
                                  "}\n"
                                  "QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
                                  "     \n"
                                  "}\n"
                                  "QHeaderView::down-arrow {                        /*设置向下排序指针*/\n"
                                  "        width: 13px;\n"
                                  "        height: 11px;\n"
                                  "        padding-right: 10px;\n"
                                  "        image: url(:/arrow_down.png);\n"
                                  "        subcontrol-position: center right;\n"
                                  "}\n"
                                  "QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
                                  "     \n"
                                  "}\n"
                                  "QTableWidget,QTableView {\n"
                                  "                font-size: 17px;                /*10榜*/                \n"
                                  "                color : rgb(1,37,116);                \n"
                                  "        border: 2px solid rgb(100, 188, 238);        \n"
                                  "        background: rgb(248,248,248);\n"
                                  "        gridline-color: rgb(196,226,255);    \n"
                                  "        text-align: center;    \n"
                                  "        outline:0px;            /*禁止焦点*/\n"
                                  "        \n"
                                  "}\n"
                                  "QTableWidget::item,QTableView::item {                            /*设置视图项*/\n"
                                  "        padding-left: 5px;\n"
                                  "        padding-right: 5px;\n"
                                  "        border: none; \n"
                                  "        background: rgba(251,251,253,200);\n"
                                  "       \n"
                                  "       /* border-right: 1px solid rgb(100, 188, 238); */\n"
                                  "        /*border-bottom: 1px solid rgb(100, 188, 238);*/\n"
                                  "}\n"
                                  "QTableWidget::item:selected,QTableView::item:selected {                    /*设置选中的视图项*/\n"
                                  "        background: rgba(207,230,253,200);\n"
                                  "        color : rgb(1,37,116);                \n"
                                  "}\n"
                                  " \n"
                                  " \n"
                                  "QTableView::item:alternate:!selected,QTableWidget::item:alternate:!selected,QListView::item:alternate:!selected \n"
                                  "{ \n"
                                  "    background: rgb(250,250,250); \n"
                                  "}\n"
                                  " \n"
                                  "QTableView::item:!alternate:!selected,QTableWidget::item:!alternate:!selected\n"
                                  "{ \n"
                                  "    background: rgb(240,247,254); \n"
                                  "}\n"
                                  "QScrollBar:vertical\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,0%);\n"
                                  "    margin:0px,0px,0px,0px;\n"
                                  "    padding-top:9px; \n"
                                  "    padding-bottom:9px;\n"
                                  "}\n"
                                  "QScrollBar::handle:vertical\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,25%);\n"
                                  "    border-radius:4px; \n"
                                  "    min-height:20;\n"
                                  "}\n"
                                  "QScrollBar::handle:vertical:hover\n"
                                  "{\n"
                                  "    width:8px;\n"
                                  "    background:rgba(0,0,0,50%);  \n"
                                  "    border-radius:4px;\n"
                                  "    min-height:20;\n"
                                  "}\n"
                                  "QScrollBar::add-line:vertical\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/3.png);\n"
                                  "    subcontrol-position:bottom;\n"
                                  "}\n"
                                  "QScrollBar::sub-line:vertical\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/1.png);\n"
                                  "    subcontrol-position:top;\n"
                                  "}\n"
                                  "QScrollBar::add-line:vertical:hover \n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/4.png);\n"
                                  "    subcontrol-position:bottom;\n"
                                  "}\n"
                                  "QScrollBar::sub-line:vertical:hover\n"
                                  "{\n"
                                  "    height:9px;width:8px;\n"
                                  "    border-image:url(:/images/a/2.png);\n"
                                  "    subcontrol-position:top;\n"
                                  "}\n"
                                  "QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
                                  "{\n"
                                  "    background:rgba(0,0,0,10%);\n"
                                  "    border-radius:4px;\n"
                                  "}")
        self.guanxi.setObjectName("guanxi")
        self.guanxi.setColumnCount(2)
        self.guanxi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.guanxi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.guanxi.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.guanxi)
        self.la1 = QtWidgets.QLineEdit(self.centralwidget)
        self.la1.setGeometry(QtCore.QRect(530, 970, 191, 31))
        self.la1.setToolTip("")
        self.la1.setStyleSheet("background:white;\n"
                               "    padding-left:5px ;\n"
                               "    padding-top:1px ;\n"
                               "    border-bottom-left-radius:3px;\n"
                               "    border-bottom-right-radius:3px;\n"
                               "    border: 1px solid rgb(209 , 209 , 209);\n"
                               "    border-top:transparent;")
        self.la1.setObjectName("la1")
        self.wenjian = QtWidgets.QPushButton(self.centralwidget)
        self.wenjian.setGeometry(QtCore.QRect(730, 970, 51, 28))
        self.wenjian.setStyleSheet("QPushButton\n"
                                   "{\n"
                                   "    color:white;\n"
                                   "    background-color:rgb(14 , 150 , 254);\n"
                                   "    border-radius:5px;\n"
                                   "    font:15px \"微软雅黑\";\n"
                                   "}\n"
                                   "\n"
                                   ":hover\n"
                                   "{\n"
                                   "    color:white;\n"
                                   "    background-color:rgb(44 , 137 , 255);\n"
                                   "}\n"
                                   "\n"
                                   ":pressed\n"
                                   "{\n"
                                   "    color:white;\n"
                                   "    background-color:rgb(14 , 135 , 228);\n"
                                   "    padding-left:3px;\n"
                                   "    padding-top:3px;\n"
                                   "}")
        self.wenjian.setObjectName("wenjian")
        self.secret_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.secret_2.setGeometry(QtCore.QRect(530, 880, 191, 31))
        self.secret_2.setToolTip("")
        self.secret_2.setStyleSheet("background:white;\n"
                                    "    padding-left:5px ;\n"
                                    "    padding-top:1px ;\n"
                                    "    border-bottom-left-radius:3px;\n"
                                    "    border-bottom-right-radius:3px;\n"
                                    "    border: 1px solid rgb(209 , 209 , 209);\n"
                                    "    border-top:transparent;")
        self.secret_2.setObjectName("secret_2")
        self.biao = QtWidgets.QPushButton(self.centralwidget)
        self.biao.setGeometry(QtCore.QRect(730, 880, 51, 28))
        self.biao.setStyleSheet("QPushButton\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(14 , 150 , 254);\n"
                                "    border-radius:5px;\n"
                                "    font:15px \"微软雅黑\";\n"
                                "}\n"
                                "\n"
                                ":hover\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(44 , 137 , 255);\n"
                                "}\n"
                                "\n"
                                ":pressed\n"
                                "{\n"
                                "    color:white;\n"
                                "    background-color:rgb(14 , 135 , 228);\n"
                                "    padding-left:3px;\n"
                                "    padding-top:3px;\n"
                                "}")
        self.biao.setObjectName("biao")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(530, 840, 141, 31))
        self.label.setStyleSheet("font: 12pt \"楷体\";\n"
                                 "color: rgb(170, 170, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 930, 141, 31))
        self.label_2.setStyleSheet("font: 12pt \"楷体\";\n"
                                   "color: rgb(170, 170, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.wenjian.clicked.connect(lambda: self.wenj(MainWindow))
        self.biao.clicked.connect(lambda: self.bia(MainWindow))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.tableWidget_6.verticalHeader().setHidden(True)
        self.shuchu.verticalHeader().setHidden(True)
        self.guanxi.verticalHeader().setHidden(True)
        self.fenjiefu.verticalHeader().setHidden(True)
        self.guanjianzi.verticalHeader().setHidden(True)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.shuchu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "单词"))
        item = self.shuchu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "二元序列"))
        item = self.shuchu.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类型"))
        item = self.shuchu.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "位置（行，列）"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "指针"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "算术运算符"))
        item = self.guanjianzi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "指针"))
        item = self.guanjianzi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "关键字"))
        item = self.fenjiefu.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "指针"))
        item = self.fenjiefu.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "分界符"))
        item = self.guanxi.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "指针"))
        item = self.guanxi.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "关系运算符"))
        self.wenjian.setText(_translate("MainWindow", "确定"))
        self.biao.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "请输入txt文件"))
        self.label_2.setText(_translate("MainWindow", "请输入表文件"))

    def bia(self, MainWindow):
        main.main(self.secret_2.text())
        self.renewbiao()

    def wenj(self, MainWindow):
        main.createbiao(self.la1.text())
        self.renewbiao()

    def renewbiao(self):
        self.shuchu.setColumnCount(4)
        self.shuchu.setRowCount(len(main.result) - 1)
        self.guanjianzi.setColumnCount(2)
        self.guanjianzi.setRowCount(len(main.k) - 1)
        self.fenjiefu.setColumnCount(2)
        self.fenjiefu.setRowCount(len(main.s) - 1)
        self.guanxi.setColumnCount(2)
        self.guanxi.setRowCount(len(main.rop) - 1)
        self.tableWidget_6.setColumnCount(2)
        self.tableWidget_6.setRowCount(len(main.aop) - 1)
        for i in range(len(main.k)):
            self.guanjianzi.setItem(i - 1, 0, QTableWidgetItem(str(i)))
            self.guanjianzi.setItem(i - 1, 1, QTableWidgetItem(main.k[i - 1]))
        for i in range(len(main.s)):
            self.fenjiefu.setItem(i - 1, 0, QTableWidgetItem(str(i)))
            self.fenjiefu.setItem(i - 1, 1, QTableWidgetItem(main.s[i - 1]))
        for i in range(len(main.rop)):
            self.guanxi.setItem(i - 1, 0, QTableWidgetItem(str(i)))
            self.guanxi.setItem(i - 1, 1, QTableWidgetItem(main.rop[i - 1]))
        for i in range(len(main.aop)):
            self.tableWidget_6.setItem(i - 1, 0, QTableWidgetItem(str(i)))
            self.tableWidget_6.setItem(i - 1, 1, QTableWidgetItem(main.aop[i - 1]))
        for i in range(len(main.result)):
            self.shuchu.setItem(i - 1, 0, QTableWidgetItem(main.result[i][0]))
            self.shuchu.setItem(i - 1, 1, QTableWidgetItem(main.result[i][1]))
            self.shuchu.setItem(i - 1, 2, QTableWidgetItem(main.result[i][2]))
            self.shuchu.setItem(i - 1, 3, QTableWidgetItem(main.result[i][3]))


def go():
    app = QtWidgets.QApplication(sys.argv)
    aw = Ui_MainWindow()
    w = QtWidgets.QMainWindow()
    aw.setupUi(w)
    w.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    go()
